// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJIZEvj9xOt8raX9K3pUg8ueQ3tiEyzg',
    appId: '1:24043943091:web:0a8882e7b8cacbd09f6cc6',
    messagingSenderId: '24043943091',
    projectId: 'whatsapp-me-75d88',
    authDomain: 'whatsapp-me-75d88.firebaseapp.com',
    storageBucket: 'whatsapp-me-75d88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6m3LrUXVGdxaYVT9r5kZ0dgNGHU26GVI',
    appId: '1:24043943091:android:10433a2fed13ca519f6cc6',
    messagingSenderId: '24043943091',
    projectId: 'whatsapp-me-75d88',
    storageBucket: 'whatsapp-me-75d88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADaZ_Lmip0997HXLq8Xjoc4bRmeZTnoLo',
    appId: '1:24043943091:ios:9a9cb845d9c5a3959f6cc6',
    messagingSenderId: '24043943091',
    projectId: 'whatsapp-me-75d88',
    storageBucket: 'whatsapp-me-75d88.appspot.com',
    iosBundleId: 'com.example.whatsappMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADaZ_Lmip0997HXLq8Xjoc4bRmeZTnoLo',
    appId: '1:24043943091:ios:720944dcd945ffc09f6cc6',
    messagingSenderId: '24043943091',
    projectId: 'whatsapp-me-75d88',
    storageBucket: 'whatsapp-me-75d88.appspot.com',
    iosBundleId: 'com.example.whatsappMe.RunnerTests',
  );
}
